version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: marketo-demo
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: marketo_demo
      DB_USERNAME: root
      DB_PASSWORD: demo
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: marketo_demo
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_PASSWORD: demo
